#!/bin/bash -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

if test -d /service
then
  echo '/service exists. I assume that svscan is already running.'
  exit 0
fi

echo 'Creating /service...'
mkdir /service


if [[ -n $(uname -a | egrep "Ubuntu|CentOS-6|el6") ]]; then 
	echo "Using Upstart";
	package/run-upstart 
else 
	echo "Using Inittab"; 
	package/run-inittab
fi
